### PR TITLE
Added Comment Threading

### PR DESCRIPTION
**Pull request by rafaykhurram**
1. Added the display of replies for every comment.
2. Added the AddReply input for adding new replies.
3. Fixed AddReply route and util functions.

### CODE REVIEW

**Comment by stephen8chang** [comment]
Code syntax and style look good; does this code support a single level for the comment thread?

**Comment by rafaykhurram** [comment]
> Code syntax and style look good; do these commits support a single level for the comment thread?

It supports more than a single level. The ReplysList component recursively calls itself. It successfully went two levels deep during testing.

**Comment by stephen8chang** [comment]
Could be a design opinion from me, but personally, I wouldn't want more than 1 level in terms of replies. Think Facebook comments

**Comment by rafaykhurram** [comment]
> Could be a design opinion from me, but personally, I wouldn't want more than 1 level in terms of replies. Think Facebook comments. Anything more than 1 level and it could look very messy in terms of the UI

Latest commit has the replies only going 1 level deep.

Should a reply automatically contain an @ towards the user whose post is being replied to like Facebook?

**Comment by stephen8chang** [comment]
> Should a reply automatically contain an @ towards the user whose post is being replied to like Facebook?

Yeah this is okay

**Comment by rafaykhurram** [comment]
> > Should a reply automatically contain an @ towards the user whose post is being replied to like Facebook?
> 
> Yeah this is okay, in my opinion

I think this issue is done.

**Comment by rafaykhurram** [comment]
> > > Should a reply automatically contain an @ towards the user whose post is being replied to like Facebook?
> > 
> > 
> > Yeah this is okay, in my opinion
> 
> I think this issue is done.

Should I close the issue?

**Pull request merged**
